name: Deploy

on:
  push:
    branches:
      - main
      - dev
      - dev2
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to Repo
        uses: actions/checkout@v2
      #  with:
      #    lfs: false
      #- name: LFS Objects
      #    run: git lfs checkout
      - name: Heroku Deploy
        uses: khlam/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          docker_heroku_process_type: "worker"